name: Run Infection

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
  workflow_dispatch:

jobs:
  mutation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.4 ]
        laravel: [ 12.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 12.*
            testbench: ^10.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, redis
          coverage: pcov

      - name: Install dependencies
        run: |
          composer config http-basic.composer.fluxui.dev "${{ secrets.FLUXUI_USERNAME }}" "${{ secrets.FLUXUI_LICENCE_KEY }}"
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer remove "larastan/larastan" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Environment
        run: |
          touch database/database.sqlite
          cp .env.testing.example .env.testing
          

      - name: Setup redis
        run: |
          docker run -d --name redis -p 6379:6379 redis:latest

      - name: Execute infection
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          REDIS_CLIENT: phpredis
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          APP_KEY: "base64:O0EpRYlMWz4zKBn/z/yLU3F8dMBZdA6N02bvkPGavP8="
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}
        run: |
          cp phpunit.xml.dist phpunit.xml
          php -d memory_limit=1G ./vendor/bin/infection --only-covering-test-cases --min-msi=50 --min-covered-msi=40

